name: snn
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.4
  - numpy=1.18.1
  - scipy=1.3.1
  - pytorch=1.2.0  # pytorch channel
  - cpuonly=1.0  # pytorch without GPU support
  - matplotlib-base=3.1.3
  - pandas=1.0.3
  - networkx=2.3
  - gudhi=2.3.0  # conda-forge channel
  - tqdm=4.44.1
