name: snn
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.4
  - numpy=1.18.1
  - scipy=1.3.1
  - pytorch=1.2.0  # pytorch channel
  - cpuonly=1.0  # pytorch without GPU support
  - matplotlib-base=3.1.3
  - pandas=1.0.3
  - networkx=2.3
  - gudhi=2.3.0  # conda-forge channel
  - tqdm=4.44.1
# dependencies of the above
  - blas=1.0=mkl
  - boost-cpp=1.69.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cgal-cpp=4.14
  - cycler=0.10.0
  - decorator=4.4.2
  - eigen=3.3.7
  - freetype=2.9.1
  - gmp=6.1.2
  - gudhi=2.3.0
  - icu=58.2
  - intel-openmp=2019.4
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mpfr=4.0.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pip=20.0.2
  - pycparser=2.20
  - pyparsing=2.4.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
