name: snn
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.7
  - numpy=1.16.2
  - scipy=1.2.1
  - pandas=0.24.2
  - matplotlib-base=3.0.3
  - gudhi=2.3.0
  - networkx=2.2
  - pygsp=0.5.1
  - tqdm=4.31.1
  - pytorch=1.0.1
# dependencies
  - boost-cpp=1.67.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.2
  - cgal=4.12
  - cycler=0.10.0
  - decorator=4.4.0
  - freetype=2.10.0
  - gmp=6.1.2
  - icu=58.2
  - kiwisolver=1.0.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - liblapack=3.8.0
  - libpng=1.6.36
  - mpfr=4.0.1
  - ncurses=6.1
  - ninja=1.9.0
  - openssl=1.1.1b
  - pip=19.0.3
  - pycparser=2.19
  - pyparsing=2.3.1
  - python-dateutil=2.8.0
  - pytz=2018.9
  - readline=7.0
  - setuptools=40.9.0
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=6.0.2
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - cudatoolkit=10.0.130
  - intel-openmp=2019.3
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - mkl=2019.3
